const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { URL } = require('url');
const { execFile } = require('child_process');
const { Store } = require('./db/store');

const PORT = Number(process.env.PORT || 3000);
const ROOT = path.join(__dirname, 'public');
const DATA_DIR = path.join(__dirname, 'data');
const UPLOAD_DIR = path.join(DATA_DIR, 'evidence');
const TEMP_DIR = path.join(DATA_DIR, 'tmp');
const FILES = {
  users: path.join(DATA_DIR, 'users.json'), sessions: path.join(DATA_DIR, 'sessions.json'), scans: path.join(DATA_DIR, 'scans.json'),
  reports: path.join(DATA_DIR, 'reports.json'), scams: path.join(DATA_DIR, 'scams.json'), deepchecks: path.join(DATA_DIR, 'deepchecks.json'),
  audit: path.join(DATA_DIR, 'audit.json'), 'saved-checks': path.join(DATA_DIR, 'saved-checks.json'), notifications: path.join(DATA_DIR, 'notifications.json'),
  'password-resets': path.join(DATA_DIR, 'password-resets.json'), 'api-keys': path.join(DATA_DIR, 'api-keys.json'), payments: path.join(DATA_DIR, 'payments.json'),
  'webhook-events': path.join(DATA_DIR, 'webhook-events.json')
};
for (const dir of [DATA_DIR, UPLOAD_DIR, TEMP_DIR]) fs.mkdirSync(dir, { recursive: true });
for (const f of Object.values(FILES)) if (!fs.existsSync(f)) fs.writeFileSync(f, '[]');

const IS_PROD = process.env.NODE_ENV === 'production';
const DB_URL = process.env.DATABASE_URL || '';
const store = new Store({ root: __dirname, files: FILES, databaseUrl: DB_URL });
const rate = new Map();
let s3Client = null;

function now() { return new Date().toISOString(); }
function id(prefix='') { return prefix + crypto.randomUUID(); }
function cleanText(v, max=5000) { return String(v ?? '').trim().slice(0, max); }
function normalizeTarget(v) { return cleanText(v, 300).toLowerCase().replace(/^https?:\/\//, '').replace(/^www\./, '').replace(/[?#].*$/, '').replace(/\/$/,''); }
function json(res, status, payload, headers={}) {
  res.writeHead(status, {'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin', ...headers});
  res.end(JSON.stringify(payload));
}
function cookies(req) { const raw=req.headers.cookie||''; const out={}; for(const part of raw.split(';')){const i=part.indexOf('=');if(i<0)continue;let v=part.slice(i+1).trim();try{v=decodeURIComponent(v)}catch{} out[part.slice(0,i).trim()]=v;} return out; }
function cookieSerialize(name,value,opts={}) { let out=`${name}=${encodeURIComponent(value)}`;if(opts.httpOnly)out+='; HttpOnly';if(opts.path)out+=`; Path=${opts.path}`;if(opts.sameSite)out+=`; SameSite=${opts.sameSite}`;if(opts.secure)out+='; Secure';if(opts.maxAge!=null)out+=`; Max-Age=${opts.maxAge}`;return out; }
function readRawBody(req, limit=5e6) { return new Promise((resolve,reject)=>{let chunks=[],size=0,done=false;const fail=e=>{if(!done){done=true;reject(e)}};req.on('data',c=>{if(done)return;size+=c.length;if(size>limit){req.destroy();fail(new Error('Payload too large.'));return}chunks.push(c)});req.on('end',()=>{if(done)return;done=true;resolve(Buffer.concat(chunks))});req.on('error',fail);}); }
async function body(req, limit=2e6) { const raw=await readRawBody(req,limit); if(!raw.length)return {};try{return JSON.parse(raw.toString('utf8'))}catch{throw new Error('Invalid JSON.');} }
function rateLimit(req,key,limit=50,windowMs=60000){const ip=(req.headers['x-forwarded-for']||req.socket.remoteAddress||'local').split(',')[0].trim();const k=key+':'+ip,t=Date.now(),old=rate.get(k)||[],fresh=old.filter(x=>x>t-windowMs);fresh.push(t);rate.set(k,fresh);return fresh.length<=limit;}
function hashPassword(password, salt=crypto.randomBytes(16).toString('hex')) { return new Promise((resolve,reject)=>crypto.scrypt(password,salt,64,(e,key)=>e?reject(e):resolve(`${salt}:${key.toString('hex')}`))); }
function verifyPassword(password,stored){return new Promise(resolve=>{try{const [salt,hex]=String(stored).split(':');const b=Buffer.from(hex,'hex');crypto.scrypt(password,salt,64,(e,key)=>resolve(!e&&b.length===key.length&&crypto.timingSafeEqual(b,key)));}catch{resolve(false)}});}
function validatePassword(p){return typeof p==='string'&&p.length>=8&&p.length<=128&&/[A-Za-z]/.test(p)&&/\d/.test(p);}
function validateUsername(u){return /^[A-Za-z0-9_]{3,20}$/.test(u);}
function detectType(input=''){const s=String(input).trim();if(/^(https?:\/\/|www\.)/i.test(s)||/\b(?:[a-z0-9-]+\.)+[a-z]{2,}(?:\/[^\s]*)?$/i.test(s))return'link';if(/^(?:\+?63|0)\d{10}$/.test(s.replace(/[\s-]/g,'')))return'phone';return'message';}
async function analyze(input='', forcedType=''){const text=String(input).trim(),type=forcedType||detectType(text),lower=text.toLowerCase();const indicators=[];let score=0;const add=(points,title,detail)=>{score+=points;indicators.push({title,detail});};
  if(type==='link'){
    if(/https?:\/\/[^/]*@(?!$)/i.test(text))add(25,'Embedded redirect pattern','An @ sign can disguise the real destination in a URL.');
    if(/^https?:\/\/(?:bit\.ly|tinyurl\.com|t\.co|goo\.gl)\//i.test(text))add(18,'Shortened URL','Shortened links can hide the final destination. Verify before opening.');
    if(/login|verify|secure|account|wallet|claim|gcash|maya|bank|otp|password/i.test(text))add(16,'Credential or payment lure','The URL contains terms commonly used in phishing or account-takeover lures.');
    if(/[а-яА-Я]|xn--/u.test(text))add(10,'Lookalike-domain signal','Non-standard characters or punycode deserve extra scrutiny.');
    if(/\.(zip|mov|click|top|xyz|site|icu)\b/i.test(text))add(9,'Higher-risk TLD signal','This signal alone does not prove fraud; verify the site independently.');
    if(!/^https:\/\//i.test(text))add(4,'Not HTTPS','Do not enter sensitive information on an unencrypted site.');
    if(/\b(facebook|gcash|maya|paypal|bpi|bdo|unionbank|google|microsoft|apple)\b/i.test(text)&&!/(facebook\.com|gcash\.com|maya\.ph|paypal\.com|bpi\.com\.ph|bdo\.com\.ph|unionbankph\.com|google\.com|microsoft\.com|apple\.com)/i.test(text))add(22,'Possible brand impersonation','The URL mentions a known brand but does not match an obvious official domain.');
    const db=await store.findScam(normalizeTarget(text)); if(db)add(db.status==='confirmed_scam'?70:db.status==='suspicious'?45:20,'Community database match',`${db.reports||0} public report(s) are associated with this URL/domain in the ScamCheck database.`);
  }
  if(type==='phone'){
    const normalized=text.replace(/[\s-]/g,''); if(/^(\+?63|0)9/.test(normalized))add(2,'Philippine mobile number','This looks like a Philippine mobile number.');
    const db=await store.findScam(normalizeTarget(normalized));if(db)add(db.status==='confirmed_scam'?70:db.status==='suspicious'?45:20,'Community database match',`${db.reports||0} public report(s) are associated with this number in the ScamCheck database.`);
  }
  if(/send\s+(?:me\s+)?money|pay\s+(?:first|now)|pay\s+(?:₱|php\s*)?[\d,]+.*(?:fee|deposit)|processing fee|registration fee|deposit/i.test(text))add(28,'Upfront payment request','Requests for money before a prize, job, delivery, or service are a strong scam indicator.');
  if(/otp|one[- ]time password|verification code|security code/i.test(text))add(24,'OTP / verification-code request','Never share a one-time code with another person.');
  if(/urgent|immediately|act now|last chance|today only|account will be closed/i.test(text))add(16,'Urgency or pressure','Pressure tactics reduce the time available to verify a claim.');
  if(/you (?:have )?won|congratulations|lucky winner|free money|prize/i.test(text))add(18,'Prize / free-money lure','Unexpected prizes or easy-money claims commonly appear in scams.');
  if(/work from home|no experience|earn\s*₱?\s*\d+[\d,]*\s*(?:per day|daily)|hiring urgently/i.test(text))add(14,'Job-offer signal','Unrealistic compensation or urgency can indicate a fake recruitment scheme.');
  if(/click (?:this )?link|open (?:this )?link|verify your account|confirm your identity/i.test(text))add(14,'Phishing call-to-action','The message pushes you toward a link or verification action.');
  if(/investment|guaranteed profit|double your money|crypto profit/i.test(text))add(20,'Investment promise','Guaranteed or unusually high returns are a common fraud signal.');
  if(/refund|delivery failed|parcel|lazada|shopee|courier/i.test(text))add(8,'Delivery / refund theme','Delivery and refund impersonation are common social-engineering themes.');
  if(/courier|parcel|delivery|lazada|shopee/i.test(text)&&/(fee|pay|payment|charge|re-deliver|redelivery)/i.test(text))add(14,'Delivery-payment request','Fake courier messages often ask for small fees or payment through an untrusted link.');
  if(type!=='phone'){const db=await store.findScam(normalizeTarget(text));if(db)add(db.status==='confirmed_scam'?70:db.status==='suspicious'?45:20,'Community database match',`${db.reports||0} public report(s) are associated with this entry.`);}
  score=Math.min(100,score);let risk='low';if(score>=70)risk='high';else if(score>=45)risk='suspicious';else if(score>=25)risk='moderate';
  const recommendations=risk==='high'?['Do not send money or verification codes.','Do not open suspicious links.','Verify the person or company using an official channel.','Preserve screenshots, receipts, and other evidence.']:risk==='suspicious'?['Pause before replying or paying.','Verify the sender independently.','Avoid clicking links from the message.','Report it if the suspicious behavior continues.']:risk==='moderate'?['Pause before paying, clicking, or sharing account information.','Verify the sender through an official channel you find yourself.','Do not share OTPs, PINs, or passwords.','Save screenshots and report the incident if anything feels wrong.']:['No strong scam indicators were detected from the submitted content.','Still verify important claims independently.','A low-risk result does not guarantee that something is safe.'];
  return {type,score,risk,indicators:indicators.slice(0,8),recommendations};
}
function safeUser(u){return u?{id:u.id,email:u.email,role:u.role,status:u.status,displayName:u.displayName,username:u.username||u.displayName,createdAt:u.createdAt,emailVerified:!!u.emailVerified}:null;}
async function currentUser(req){const token=cookies(req).sc_session;if(!token)return null;const s=await store.findSessionByToken(token);if(!s)return null;const u=await store.findUserById(s.userId);return u&&u.status==='active'?u:null;}
async function requireAuth(req,res,roles=[]){const u=await currentUser(req);if(!u){json(res,401,{error:'Authentication required.'});return null;}if(roles.length&&!roles.includes(u.role)){json(res,403,{error:'Not authorized.'});return null;}return u;}
async function audit(user,action,target,meta={}){await store.audit({id:id('aud_'),at:now(),actor:user?.id||'system',action,target,meta});}
async function notify(userId,title,message,kind='info'){await store.notify({id:id('ntf_'),userId,title,message,kind,read:false,createdAt:now()});}
async function makeSession(user){const nonce=crypto.randomBytes(32).toString('hex');const secret=process.env.SESSION_SECRET||'development-session-secret';const token=nonce+'.'+crypto.createHmac('sha256',secret).update(nonce).digest('hex');await store.createSession({token,userId:user.id,createdAt:now(),expiresAt:new Date(Date.now()+30*24*60*60*1000).toISOString()});return token;}
async function uniqueReportId(){let x;for(let i=0;i<20;i++){x='SC-'+new Date().getFullYear()+'-'+crypto.randomInt(100000,999999);if(!(await store.findReport(x)))return x;}return 'SC-'+new Date().getFullYear()+'-'+Date.now();}
function validateImageData(ev){const mime=cleanText(ev.mime,80),dataUrl=String(ev.dataUrl||'');if(!/^image\/(png|jpeg|webp)$/.test(mime))return null;if(!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(dataUrl)||dataUrl.length>2200000)return null;const buf=Buffer.from(dataUrl.split(',')[1],'base64');if(buf.length>1600000)return null;return{mime,buf,name:cleanText(ev.name,120)};}
function storageConfigured(){return !IS_PROD || (process.env.STORAGE_PROVIDER||'').toLowerCase()==='s3';}
async function getS3(){if(s3Client)return s3Client;if((process.env.STORAGE_PROVIDER||'').toLowerCase()!=='s3')return null;const {S3Client}=require('@aws-sdk/client-s3');s3Client=new S3Client({region:process.env.S3_REGION||'auto',endpoint:process.env.S3_ENDPOINT||undefined,forcePathStyle:process.env.S3_FORCE_PATH_STYLE==='true'});return s3Client;}
async function saveEvidenceArray(evidence,max=3){const out=[];for(const ev of Array.isArray(evidence)?evidence.slice(0,max):[]){const v=validateImageData(ev);if(!v)continue;const ext=v.mime==='image/png'?'png':v.mime==='image/webp'?'webp':'jpg';const fn=crypto.randomUUID()+'.'+ext;const key=`evidence/${new Date().toISOString().slice(0,10)}/${fn}`;if(IS_PROD&& !storageConfigured())throw new Error('Evidence storage is not configured for production.');if((process.env.STORAGE_PROVIDER||'').toLowerCase()==='s3'){const client=await getS3();const {PutObjectCommand}=require('@aws-sdk/client-s3');await client.send(new PutObjectCommand({Bucket:process.env.S3_BUCKET,Key:key,Body:v.buf,ContentType:v.mime,Metadata:{originalname:encodeURIComponent(v.name||fn)}}));out.push({id:id('ev_'),fileName:v.name||fn,mime:v.mime,size:v.buf.length,storageKey:key});}else{fs.writeFileSync(path.join(UPLOAD_DIR,fn),v.buf,{flag:'wx'});out.push({id:id('ev_'),fileName:v.name||fn,mime:v.mime,size:v.buf.length,storageKey:fn,file:fn});}}
  return out;
}
function runOcr(buf,mime){return new Promise((resolve,reject)=>{const ext=mime==='image/png'?'png':mime==='image/webp'?'webp':'jpg';const fn=path.join(TEMP_DIR,crypto.randomUUID()+'.'+ext);fs.writeFileSync(fn,buf,{flag:'wx'});execFile('tesseract',[fn,'stdout','-l','eng','--psm','6'],{timeout:12000,maxBuffer:200000},(err,stdout)=>{try{fs.unlinkSync(fn)}catch{};if(err)return reject(new Error('OCR could not process this image.'));resolve(cleanText(stdout,12000));});});}
function tesseractAvailable(){return fs.existsSync('/usr/bin/tesseract')||fs.existsSync('/usr/local/bin/tesseract');}
async function sendEmail({to,subject,html}){
  if((process.env.EMAIL_PROVIDER||'').toLowerCase()!=='resend'){
    if(IS_PROD) throw new Error('Transactional email is not configured.');
    return {mode:'development'};
  }
  const key=process.env.RESEND_API_KEY,from=process.env.RESEND_FROM;if(!key||!from)throw new Error('Resend email configuration is incomplete.');
  const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[to],subject,html})});if(!r.ok){const txt=await r.text();throw new Error(`Email provider error: ${txt.slice(0,300)}`);}return r.json();
}
async function createToken(kind,userId,ttlMs){const token=crypto.randomBytes(24).toString('hex'),rec={kind,userId,tokenHash:crypto.createHash('sha256').update(token).digest('hex'),createdAt:now(),expiresAt:new Date(Date.now()+ttlMs).toISOString()};await store.createReset(rec);return token;}
function verifyPayMongoSignature(raw,header,secret,mode){if(!secret||!header) return false;const p={};for(const part of String(header).split(',')){const i=part.indexOf('=');if(i>0)p[part.slice(0,i).trim()]=part.slice(i+1).trim();}const ts=Number(p.t);const sig=mode==='live'?p.li:p.te;if(!Number.isFinite(ts)||!sig)return false;if(Math.abs(Date.now()/1000-ts)>300)return false;const expected=crypto.createHmac('sha256',secret).update(`${p.t}.${raw}`).digest('hex');try{return crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(sig));}catch{return false;}}
async function createPayMongoCheckout(order,user){const key=process.env.PAYMONGO_SECRET_KEY;if(!key)throw new Error('PayMongo is not configured.');const base=process.env.APP_BASE_URL;if(!base)throw new Error('APP_BASE_URL is required for online checkout.');const attrs={line_items:[{name:'DeepCheck Investigation',amount:5000,currency:'PHP',quantity:1}],payment_method_types:(process.env.PAYMONGO_PAYMENT_METHODS||'gcash,paymaya,qrph,card').split(',').map(x=>x.trim()).filter(Boolean),success_url:`${base}/#deepcheck-success=${encodeURIComponent(order.orderId)}`,cancel_url:`${base}/#deepcheck-cancel=${encodeURIComponent(order.orderId)}`,reference_number:order.orderId,description:'ScamCheck PH DeepCheck Investigation',send_email_receipt:false,billing:{name:user.displayName,email:user.email},metadata:{order_id:order.orderId}};const r=await fetch('https://api.paymongo.com/v2/checkout_sessions',{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${key}:`).toString('base64')}`,'Content-Type':'application/json','Idempotency-Key':order.orderId},body:JSON.stringify({data:{attributes:attrs}})});const payload=await r.json();if(!r.ok)throw new Error(payload?.errors?.[0]?.detail||'Unable to create PayMongo checkout.');const a=payload.data?.attributes||{};return{id:payload.data?.id,checkoutUrl:a.checkout_url,status:a.status};}
function serveFile(req,res,pathname){let file=pathname==='/'?path.join(ROOT,'index.html'):path.join(ROOT,pathname.replace(/^\/+/,''));if(!file.startsWith(ROOT))return json(res,403,{error:'Forbidden'});fs.stat(file,(err,stat)=>{if(err||!stat.isFile())return json(res,404,{error:'Not found'});const ext=path.extname(file).toLowerCase();const types={'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp','.webmanifest':'application/manifest+json'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':ext==='.html'||ext==='.json'?'no-cache':'public, max-age=86400'});fs.createReadStream(file).pipe(res);});}

async function seed(){
  await store.seed();
  const adminEmail=process.env.ADMIN_EMAIL||'admin@scamcheck.ph', adminPassword=process.env.ADMIN_PASSWORD||'ChangeMe123!';
  const existing=await store.findUserByEmail(adminEmail);
  if(!existing){const passwordHash=await hashPassword(adminPassword);await store.insertUser({id:id('usr_'),email:adminEmail,passwordHash,username:'admin',role:'admin',status:'active',createdAt:now(),displayName:'ScamCheck Admin',emailVerified:true});}
}

const server=http.createServer(async(req,res)=>{
  try{
    const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);
    res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');
    if(req.method==='GET'&&u.pathname==='/api/health') return json(res,200,{ok:true,service:'ScamCheck PH',version:'6.0.0',storage:store.usePg?'postgresql':'json',payments:(process.env.PAYMONGO_SECRET_KEY?'paymongo':'demo'),email:(process.env.EMAIL_PROVIDER||'development'),evidence:((process.env.STORAGE_PROVIDER||'local').toLowerCase()),ocr:tesseractAvailable(),time:now()});
    if(req.method==='POST'&&u.pathname==='/api/webhooks/paymongo'){
      const raw=(await readRawBody(req,2e6)).toString('utf8');const header=req.headers['paymongo-signature']||req.headers['x-paymongo-signature'];const mode=(process.env.PAYMONGO_SECRET_KEY||'').startsWith('sk_live_')?'live':'test';if(!verifyPayMongoSignature(raw,header,process.env.PAYMONGO_WEBHOOK_SECRET,mode))return json(res,401,{error:'Invalid webhook signature.'});let event;try{event=JSON.parse(raw)}catch{return json(res,400,{error:'Invalid webhook JSON.'});}const eventKey=event?.data?.id||event?.id;if(!eventKey)return json(res,400,{error:'Webhook event ID missing.'});if(!(await store.recordWebhookEvent('paymongo',eventKey,event)))return json(res,200,{ok:true,duplicate:true});const eventType=event?.data?.attributes?.type||event?.data?.type||event?.type;const session=event?.data?.attributes?.data||event?.data?.data||event?.data?.attributes;const reference=session?.attributes?.reference_number||session?.attributes?.metadata?.order_id; if(eventType==='checkout_session.payment.paid'&&reference){const order=await store.findDeepcheckByOrder(reference);if(order&&order.status!=='investigation_ready'&&order.status!=='completed'){order.status='investigation_ready';order.updatedAt=now();order.result={...(order.result||{}),investigationStatus:'ready_for_review',paymentVerified:true};await store.updateDeepcheck(order);await store.updatePaymentByOrder(order.orderId,{providerReference:session?.id||session?.data?.id||null,status:'paid',metadata:{eventKey}});await notify(order.userId,'Payment received',`${order.orderId} is now paid and ready for investigation review.`,'success');await audit(null,'paymongo_payment_paid',order.orderId,{eventKey});}}return json(res,200,{ok:true});
    }
    if(req.method==='GET'&&u.pathname==='/api/stats'){return json(res,200,await store.stats());}
    if(req.method==='POST'&&u.pathname==='/api/auth/register'){
      if(!rateLimit(req,'register',10,600000))return json(res,429,{error:'Too many sign-up attempts. Please try again later.'});const d=await body(req,100000),email=cleanText(d.email,160).toLowerCase(),password=String(d.password||''),displayName=cleanText(d.displayName,80)||email.split('@')[0],username=cleanText(d.username,20).toLowerCase();
      if(!/^\S+@\S+\.\S+$/.test(email))return json(res,400,{error:'Enter a valid email address.'});if(!validateUsername(username))return json(res,400,{error:'Username must be 3–20 characters using letters, numbers, or underscores.'});if(!validatePassword(password))return json(res,400,{error:'Password must be 8–128 characters and include at least one letter and one number.'});if(await store.findUserByEmail(email))return json(res,409,{error:'An account with this email already exists.'});const users=await store.listUsers();if(users.some(x=>(x.username||'').toLowerCase()===username))return json(res,409,{error:'That username is already taken.'});
      const user={id:id('usr_'),email,passwordHash:await hashPassword(password),username,role:'user',status:'active',createdAt:now(),displayName,emailVerified:false};await store.insertUser(user);const session=await makeSession(user);await audit(user,'account_created',user.id,{});await notify(user.id,'Welcome to ScamCheck PH','Your account is ready. Keep checking before you trust links, sellers, jobs, and payment requests.','success');const token=await createToken('verify',user.id,24*60*60*1000);let devVerificationToken;let emailSendFailed=false;try{await sendEmail({to:user.email,subject:'Verify your ScamCheck PH email',html:`<p>Hi ${cleanText(user.displayName,80)},</p><p>Verify your ScamCheck PH email using this token:</p><p><strong>${token}</strong></p><p>This token expires in 24 hours.</p>`});}catch(e){if(IS_PROD){emailSendFailed=true;console.error('Email send failed in production:',e.message);}else{throw e;}}if(!IS_PROD)devVerificationToken=token;return json(res,201,{user:safeUser(user),verificationRequired:true,devVerificationToken}, {'Set-Cookie':cookieSerialize('sc_session',session,{httpOnly:true,path:'/',sameSite:'Lax',secure:IS_PROD,maxAge:30*24*60*60})});
    }
    if(req.method==='POST'&&u.pathname==='/api/auth/login'){
      if(!rateLimit(req,'login',20,600000))return json(res,429,{error:'Too many login attempts. Please try again later.'});const d=await body(req,100000),email=cleanText(d.email,160).toLowerCase(),password=String(d.password||''),user=await store.findUserByEmail(email);if(!user||!(await verifyPassword(password,user.passwordHash)))return json(res,401,{error:'Email or password is incorrect.'});if(user.status!=='active')return json(res,403,{error:`This account is ${user.status}.`});const session=await makeSession(user);await audit(user,'login',user.id,{});return json(res,200,{user:safeUser(user)},{'Set-Cookie':cookieSerialize('sc_session',session,{httpOnly:true,path:'/',sameSite:'Lax',secure:IS_PROD,maxAge:30*24*60*60})});
    }
    if(req.method==='POST'&&u.pathname==='/api/auth/logout'){const token=cookies(req).sc_session;if(token)await store.deleteSessionByToken(token);return json(res,200,{ok:true},{'Set-Cookie':cookieSerialize('sc_session','',{httpOnly:true,path:'/',sameSite:'Lax',secure:IS_PROD,maxAge:0})});}
    if(req.method==='GET'&&u.pathname==='/api/auth/me'){const user=await currentUser(req);if(!user)return json(res,401,{error:'Authentication required.'});return json(res,200,{user:safeUser(user)});}
    if(req.method==='POST'&&u.pathname==='/api/auth/verify'){const user=await requireAuth(req,res);if(!user)return;const d=await body(req,10000),token=cleanText(d.token,200),hash=crypto.createHash('sha256').update(token).digest('hex'),rec=await store.findReset('verify',user.id,hash);if(!rec)return json(res,400,{error:'Verification token is invalid or expired.'});user.emailVerified=true;user.updatedAt=now();await store.updateUser(user);await store.deleteReset(hash);await notify(user.id,'Email verified','Your email is marked as verified.','success');return json(res,200,{user:safeUser(user)});}
    if(req.method==='POST'&&u.pathname==='/api/auth/forgot'){if(!rateLimit(req,'forgot',10,600000))return json(res,429,{error:'Too many reset requests. Try again later.'});const d=await body(req,10000),email=cleanText(d.email,160).toLowerCase(),user=await store.findUserByEmail(email);if(!user)return json(res,200,{ok:true,message:'If the account exists, a reset link has been prepared.'});const token=await createToken('reset',user.id,15*60*1000);try{await sendEmail({to:user.email,subject:'Reset your ScamCheck PH password',html:`<p>Use this single-use token to reset your password:</p><p><strong>${token}</strong></p><p>It expires in 15 minutes.</p>`});}catch(e){if(IS_PROD)return json(res,503,{error:'We could not send the reset email. Please try again later.'});}return json(res,200,{ok:true,message:'Reset request created.',devResetToken:IS_PROD?undefined:token});}
    if(req.method==='POST'&&u.pathname==='/api/auth/reset'){const d=await body(req,20000),token=cleanText(d.token,200),newPassword=String(d.password||'');if(!validatePassword(newPassword))return json(res,400,{error:'Password must be 8–128 characters and include at least one letter and one number.'});const hash=crypto.createHash('sha256').update(token).digest('hex'),rec=await store.findReset('reset',undefined,hash);if(!rec)return json(res,400,{error:'Reset token is invalid or expired.'});const user=await store.findUserById(rec.userId);if(!user)return json(res,404,{error:'Account not found.'});user.passwordHash=await hashPassword(newPassword);user.updatedAt=now();await store.updateUser(user);await store.deleteReset(hash);await store.deleteSessionsForUser(user.id);await audit(user,'password_reset',user.id,{});return json(res,200,{ok:true});}
    if(req.method==='POST'&&u.pathname==='/api/auth/profile'){const user=await requireAuth(req,res);if(!user)return;const d=await body(req,30000),displayName=cleanText(d.displayName,80),username=cleanText(d.username,20).toLowerCase();if(!displayName)return json(res,400,{error:'Display name is required.'});if(!validateUsername(username))return json(res,400,{error:'Username must be 3–20 characters using letters, numbers, or underscores.'});const users=await store.listUsers();if(users.some(x=>x.id!==user.id&&(x.username||'').toLowerCase()===username))return json(res,409,{error:'That username is already taken.'});user.displayName=displayName;user.username=username;user.updatedAt=now();await store.updateUser(user);await audit(user,'profile_updated',user.id,{});return json(res,200,{user:safeUser(user)});}
    if(req.method==='POST'&&u.pathname==='/api/auth/delete'){const user=await requireAuth(req,res);if(!user)return;const d=await body(req,20000);if(!await verifyPassword(String(d.password||''),user.passwordHash))return json(res,401,{error:'Password is incorrect.'});if(user.role==='admin')return json(res,400,{error:'The seeded admin account cannot be deleted from this build.'});await store.deleteUser(user.id);await audit(null,'account_deleted',user.id,{});return json(res,200,{ok:true},{'Set-Cookie':cookieSerialize('sc_session','',{httpOnly:true,path:'/',sameSite:'Lax',secure:IS_PROD,maxAge:0})});}

    if(req.method==='POST'&&u.pathname==='/api/check'){if(!rateLimit(req,'check',120,60000))return json(res,429,{error:'Too many checks. Please slow down for a moment.'});const d=await body(req),input=cleanText(d.input,12000);if(!input)return json(res,400,{error:'Input is required.'});const result=await analyze(input,d.type||'');const user=await currentUser(req),scan={id:id('scan_'),createdAt:now(),userId:user?.id||null,inputType:result.type,result,preview:input.slice(0,180)};await store.insertScan(scan);return json(res,200,scan);}
    if(req.method==='POST'&&u.pathname==='/api/screenshot-check'){if(!rateLimit(req,'screenshot',20,60000))return json(res,429,{error:'Too many screenshot checks. Please try again shortly.'});const d=await body(req,2500000),v=validateImageData(d);if(!v)return json(res,400,{error:'Screenshot must be PNG, JPG, or WebP and 1.6 MB or smaller.'});let textExtract='';try{textExtract=await runOcr(v.buf,v.mime)}catch(e){return json(res,422,{error:e.message});}const fallback=cleanText(d.visibleText,12000),input=textExtract.trim()||fallback;if(!input)return json(res,422,{error:'No readable text was detected. Paste the visible text and try again.'});const result=await analyze(input,'message'),user=await currentUser(req),scan={id:id('scan_'),createdAt:now(),userId:user?.id||null,inputType:'screenshot',source:'ocr',ocrText:input.slice(0,12000),result,preview:input.slice(0,180)};await store.insertScan(scan);return json(res,200,scan);}
    if(req.method==='GET'&&u.pathname==='/api/scans'){const user=await requireAuth(req,res);if(!user)return;return json(res,200,{items:await store.listScansForUser(user.id)});}
    if(req.method==='GET'&&u.pathname==='/api/scams'){const q=cleanText(u.searchParams.get('q'),200).toLowerCase();return json(res,200,{items:await store.listScams(q)});}
    if(req.method==='POST'&&u.pathname==='/api/reports'){const user=await requireAuth(req,res);if(!user)return;if(!rateLimit(req,'report',30,3600000))return json(res,429,{error:'You have reached the report rate limit. Please try again later.'});const d=await body(req,3500000);if(!d.category||!d.target||!d.description)return json(res,400,{error:'Category, target and description are required.'});const evidence=await saveEvidenceArray(d.evidence);const report={id:await uniqueReportId(),createdAt:now(),status:'submitted',category:cleanText(d.category,80),target:cleanText(d.target,300),description:cleanText(d.description,5000),incidentDate:cleanText(d.eventDate,30)||null,amountLost:d.amountLost==null||d.amountLost===''?null:Number(d.amountLost)||0,userId:user.id,evidenceCount:evidence.length,reviewedAt:null,reviewedBy:null,reviewNote:null,reportCounted:false,reportCountedAt:null};await store.insertReport(report);if(evidence.length)await store.insertEvidence(report.id,evidence);await notify(user.id,'Report submitted',`${report.id} has been submitted for review.`,'success');await audit(user,'report_created',report.id,{category:report.category,target:report.target});return json(res,201,report);}
    if(req.method==='GET'&&u.pathname==='/api/reports'){const user=await requireAuth(req,res);if(!user)return;return json(res,200,{items:await store.listReportsForUser(user.id)});}
    if(req.method==='POST'&&u.pathname==='/api/deepcheck'){const user=await requireAuth(req,res);if(!user)return;if(!rateLimit(req,'deepcheck',10,3600000))return json(res,429,{error:'Too many DeepCheck requests. Please try again later.'});const d=await body(req,3500000),target=cleanText(d.target,300),type=cleanText(d.type,50)||'message',context=cleanText(d.context,5000);if(!target)return json(res,400,{error:'Target is required.'});const evidence=await saveEvidenceArray(d.evidence),order={orderId:'DC-'+new Date().getFullYear()+'-'+crypto.randomInt(100000,999999),userId:user.id,createdAt:now(),updatedAt:now(),price:50,status:'pending_payment',target,type,context,evidenceCount:evidence.length,evidence,result:{identityStatus:'UNVERIFIED',investigationStatus:'awaiting_payment',privacyNotice:'Public/legitimate evidence only; no private identity disclosure.'}};if(process.env.PAYMONGO_SECRET_KEY){const checkout=await createPayMongoCheckout(order,user);order.status='payment_pending';order.result={...order.result,paymentProvider:'paymongo',checkoutSessionId:checkout.id};await store.insertDeepcheck(order);await store.createPayment({id:id('pay_'),orderId:order.orderId,provider:'paymongo',providerReference:checkout.id,checkoutUrl:checkout.checkoutUrl,amount:50,currency:'PHP',status:'pending',createdAt:now(),updatedAt:now(),metadata:{}});return json(res,201,{...order,checkoutUrl:checkout.checkoutUrl,paymentProvider:'paymongo'});}
      if(IS_PROD)return json(res,503,{error:'Online payment is not configured. Please try again later.'});await store.insertDeepcheck(order);return json(res,201,{...order,paymentProvider:'demo'});
    }
    if(req.method==='POST'&&/^\/api\/deepcheck\/[^/]+\/demo-pay$/.test(u.pathname)){if(IS_PROD)return json(res,404,{error:'Not found.'});const user=await requireAuth(req,res);if(!user)return;const oid=decodeURIComponent(u.pathname.split('/')[3]),item=await store.findDeepcheck(oid,user.id);if(!item)return json(res,404,{error:'DeepCheck not found.'});if(item.status!=='pending_payment')return json(res,400,{error:'This DeepCheck has already been paid or completed.'});item.status='investigation_ready';item.updatedAt=now();item.result={...(item.result||{}),investigationStatus:'ready_for_review',paymentVerified:true};await store.updateDeepcheck(item);await notify(user.id,'DeepCheck started',`${oid} is ready for investigation review.`,'success');await audit(user,'deepcheck_demo_paid',oid,{price:50});return json(res,200,item);}
    if(req.method==='GET'&&/^\/api\/deepcheck\/[^/]+$/.test(u.pathname)){const user=await requireAuth(req,res);if(!user)return;const oid=decodeURIComponent(u.pathname.split('/').pop()),item=await store.findDeepcheck(oid,user.id);if(!item)return json(res,404,{error:'DeepCheck not found.'});return json(res,200,item);}
    if(req.method==='GET'&&u.pathname==='/api/my/deepchecks'){const user=await requireAuth(req,res);if(!user)return;return json(res,200,{items:await store.listDeepchecksForUser(user.id)});}
    if(req.method==='POST'&&u.pathname==='/api/saved-checks'){const user=await requireAuth(req,res);if(!user)return;const d=await body(req,30000),scanId=cleanText(d.scanId,100),scan=await store.findScanForUser(scanId,user.id);if(!scan)return json(res,404,{error:'Check not found.'});if(await store.savedExists(user.id,scanId))return json(res,409,{error:'This check is already saved.'});const item={id:id('save_'),userId:user.id,scanId,createdAt:now(),inputType:scan.inputType,preview:scan.preview,result:scan.result};await store.createSaved(item);return json(res,201,item);}
    if(req.method==='GET'&&u.pathname==='/api/saved-checks'){const user=await requireAuth(req,res);if(!user)return;return json(res,200,{items:await store.listSaved(user.id)});}
    if(req.method==='DELETE'&&/^\/api\/saved-checks\/[^/]+$/.test(u.pathname)){const user=await requireAuth(req,res);if(!user)return;const sid=decodeURIComponent(u.pathname.split('/').pop());if(!await store.deleteSaved(sid,user.id))return json(res,404,{error:'Saved check not found.'});return json(res,200,{ok:true});}
    if(req.method==='GET'&&u.pathname==='/api/notifications'){const user=await requireAuth(req,res);if(!user)return;const items=await store.listNotifications(user.id);return json(res,200,{items,unread:items.filter(x=>!x.read).length});}
    if(req.method==='POST'&&u.pathname==='/api/notifications/read-all'){const user=await requireAuth(req,res);if(!user)return;await store.markNotificationsRead(user.id);return json(res,200,{ok:true});}

    if(req.method==='GET'&&u.pathname==='/api/admin/overview'){const user=await requireAuth(req,res,['admin','moderator']);if(!user)return;const stats=await store.stats(),reports=await store.listRecentReports(),deep=await store.listRecentDeepchecks();return json(res,200,{counts:{reports:stats.reports,pendingReports:reports.filter(x=>['submitted','under_review'].includes(x.status)).length,scams:stats.knownEntities,users:stats.users,deepchecks:stats.deepchecks,checks:stats.checks,saved:stats.saved||0},recentReports:reports,recentDeepChecks:deep});}
    if(req.method==='GET'&&u.pathname==='/api/admin/users'){const user=await requireAuth(req,res,['admin']);if(!user)return;return json(res,200,{items:(await store.listUsers()).map(safeUser)});}
    if(req.method==='POST'&&/^\/api\/admin\/reports\/[^/]+\/status$/.test(u.pathname)){const user=await requireAuth(req,res,['admin','moderator']);if(!user)return;const rid=decodeURIComponent(u.pathname.split('/')[4]),d=await body(req,30000),allowed=['submitted','under_review','insufficient_evidence','suspicious','confirmed_scam','rejected','duplicate'];if(!allowed.includes(d.status))return json(res,400,{error:'Invalid status.'});const item=await store.findReport(rid);if(!item)return json(res,404,{error:'Report not found.'});item.status=d.status;item.reviewedAt=now();item.reviewedBy=user.id;item.reviewNote=cleanText(d.reviewNote,1000);const normalized=normalizeTarget(item.target);let scam=await store.findScam(normalized);if(!scam&&d.status==='confirmed_scam'){scam={id:id('sc_'),target:item.target,normalized,type:item.category,status:'confirmed_scam',reports:0,note:'Confirmed through moderator review.',lastReviewed:now()};}if(scam){if(!item.reportCounted&&['reported','suspicious','confirmed_scam'].includes(d.status)){scam.reports=Math.max(0,(scam.reports||0)+1);item.reportCounted=true;item.reportCountedAt=now();}if(['suspicious','confirmed_scam','under_review','reported','insufficient_evidence'].includes(d.status))scam.status=d.status==='confirmed_scam'?'confirmed_scam':d.status;scam.lastReviewed=now();scam.note=item.reviewNote||scam.note;await store.insertScam(scam);}await store.updateReport(item);if(item.userId)await notify(item.userId,'Report updated',`${item.id} is now ${item.status.replaceAll('_',' ')}.`,'info');await audit(user,'report_status_changed',rid,{status:d.status});return json(res,200,item);}
    if(req.method==='POST'&&u.pathname==='/api/admin/scams'){const user=await requireAuth(req,res,['admin']);if(!user)return;const d=await body(req,50000),target=cleanText(d.target,300);if(!target)return json(res,400,{error:'Target is required.'});const item={id:id('sc_'),target,normalized:normalizeTarget(target),type:cleanText(d.type,50)||'Entity',status:cleanText(d.status,50)||'reported',reports:Math.max(0,Number(d.reports||0)||0),note:cleanText(d.note,500),lastReviewed:now()};await store.insertScam(item);await audit(user,'scam_entity_created',item.id,{});return json(res,201,item);}
    if(req.method==='DELETE'&&/^\/api\/admin\/scams\/[^/]+$/.test(u.pathname)){const user=await requireAuth(req,res,['admin']);if(!user)return;const sid=decodeURIComponent(u.pathname.split('/').pop()),items=await store.listScams('');if(!items.some(x=>x.id===sid))return json(res,404,{error:'Scam entity not found.'});await store.deleteScam(sid);await audit(user,'scam_entity_deleted',sid,{});return json(res,200,{ok:true});}
    if(req.method==='POST'&&/^\/api\/admin\/users\/[^/]+\/status$/.test(u.pathname)){const user=await requireAuth(req,res,['admin']);if(!user)return;const uid=decodeURIComponent(u.pathname.split('/')[4]),d=await body(req,20000),allowed=['active','restricted','suspended','banned'];if(!allowed.includes(d.status))return json(res,400,{error:'Invalid user status.'});const item=await store.findUserById(uid);if(!item)return json(res,404,{error:'User not found.'});if(item.id===user.id&&d.status!=='active')return json(res,400,{error:'You cannot deactivate your own admin account.'});item.status=d.status;item.updatedAt=now();await store.updateUser(item);await audit(user,'user_status_changed',uid,{status:d.status});return json(res,200,{user:safeUser(item)});}
    if(req.method==='GET'&&u.pathname==='/api/admin/audit'){const user=await requireAuth(req,res,['admin']);if(!user)return;return json(res,200,{items:await store.listAudit()});}
    if(req.method==='GET'&&u.pathname==='/api/admin/scams'){const user=await requireAuth(req,res,['admin']);if(!user)return;return json(res,200,{items:await store.listScams('')});}
    if(req.method==='POST'&&u.pathname==='/api/admin/api-keys'){const user=await requireAuth(req,res,['admin']);if(!user)return;const d=await body(req,20000),name=cleanText(d.name,80)||'Unnamed key',raw='sc_'+crypto.randomBytes(24).toString('hex'),hash=crypto.createHash('sha256').update(raw).digest('hex'),item={id:id('key_'),name,hash,createdAt:now(),revoked:false,createdBy:user.id};await store.createApiKey(item);await audit(user,'api_key_created',item.id,{name});return json(res,201,{id:item.id,name:item.name,createdAt:item.createdAt,key:raw});}
    if(req.method==='GET'&&u.pathname==='/api/admin/api-keys'){const user=await requireAuth(req,res,['admin']);if(!user)return;return json(res,200,{items:(await store.listApiKeys()).map(x=>({id:x.id,name:x.name,createdAt:x.createdAt,revoked:x.revoked}))});}
    if(req.method==='POST'&&/^\/api\/admin\/api-keys\/[^/]+\/revoke$/.test(u.pathname)){const user=await requireAuth(req,res,['admin']);if(!user)return;const kid=decodeURIComponent(u.pathname.split('/')[4]),item=await store.revokeApiKey(kid);if(!item)return json(res,404,{error:'API key not found.'});await audit(user,'api_key_revoked',kid,{});return json(res,200,{ok:true});}
    if(req.method==='POST'&&u.pathname==='/api/v1/check'){const auth=String(req.headers.authorization||'');if(!auth.startsWith('Bearer '))return json(res,401,{error:'API key required.'});const raw=auth.slice(7),hash=crypto.createHash('sha256').update(raw).digest('hex'),key=await store.findApiKey(hash);if(!key)return json(res,401,{error:'Invalid API key.'});const d=await body(req,100000),input=cleanText(d.input,12000);if(!input)return json(res,400,{error:'Input is required.'});return json(res,200,{type:'api',source:'ScamCheck PH API',result:await analyze(input,d.type||'')});}
    if(req.method==='GET')return serveFile(req,res,u.pathname);
    return json(res,405,{error:'Method not allowed.'});
  }catch(err){console.error(err);if(!res.headersSent)json(res,500,{error:'Server error.',detail:IS_PROD?'Unexpected error':err.message});}
});

(async()=>{try{await store.init();await seed();server.listen(PORT,()=>console.log(`ScamCheck PH v6 running on http://localhost:${PORT} (${store.usePg?'PostgreSQL':'JSON'})`));}catch(err){console.error('Startup failed',err);process.exit(1);}})();
process.on('SIGTERM',async()=>{server.close();await store.close();process.exit(0)});
